#!/usr/bin/env python3
"""Step 2 - OCR cleaning, fully logged.

clean_text / clean_with_log normalize raw ALTO-derived OCR for analysis:
NFKC + encoding repair, character fixes, de-hyphenation across line breaks,
boilerplate/header removal, whitespace normalization. Word-splitting that
needs a lexicon (e.g. 'Disor ders' -> 'Disorders') is left to manual
curation so meaning is never silently changed.

Run `python scripts/clean_ocr.py` to clean every page in data/raw/ocr/ into
data/cleaned/ and write a JSON transformation log. The per-claim raw->corrected
pairs that actually feed the analysis live in data/cleaned/cleaning_log.csv,
generated by build_pipeline.py from the verified extractions.
"""
from pathlib import Path
import re, json, unicodedata

CHAR_FIXES = {"\u2014":"-","\u2018":"'","\u2019":"'","\u201c":'"',"\u201d":'"',
              "\u00ad":"","\ufb01":"fi","\ufb02":"fl"}
BOILERPLATE = [re.compile(r"(?im)^\s*page\s+\d+\b.*$"), re.compile(r"(?im)^\s*\d+\s*$")]

def clean_with_log(raw):
    log=[]; txt=raw
    def rec(k,a,b):
        if a!=b: log.append({"transform":k})
    b=txt; txt=unicodedata.normalize("NFKC",txt); rec("unicode_nfkc",b,txt)
    b=txt
    for x,y in CHAR_FIXES.items(): txt=txt.replace(x,y)
    rec("char_fix",b,txt)
    b=txt; txt=re.sub(r"(\w)[-\u00ad]\s*\n\s*(\w)",r"\1\2",txt); rec("dehyphenate_linebreak",b,txt)
    b=txt
    for p in BOILERPLATE: txt=p.sub("",txt)
    rec("strip_boilerplate",b,txt)
    b=txt; txt=re.sub(r"[ \t]+"," ",txt); txt=re.sub(r"\n{3,}","\n\n",txt).strip(); rec("normalize_whitespace",b,txt)
    return txt, log

def clean_text(raw): return clean_with_log(raw)[0]

def main():
    root=Path(__file__).resolve().parents[1]
    src=root/"data"/"raw"/"ocr"; out=root/"data"/"cleaned"; out.mkdir(parents=True,exist_ok=True)
    manifest=[]
    for f in sorted(src.glob("*.txt")):
        cleaned,log=clean_with_log(f.read_text(encoding="utf-8",errors="replace"))
        (out/f.name.replace(".txt",".clean.txt")).write_text(cleaned,encoding="utf-8")
        manifest.append({"file":f.name,"n_transform_groups":len(log)})
    (out/"_cleaning_manifest.json").write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding="utf-8")
    print(f"Cleaned {len(manifest)} pages -> data/cleaned/")

if __name__=="__main__": main()
